{% set name = "metocean-stats" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 799c70ddb954713469c445c42640a0bddba83981924d69f856ca8ac813353800

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.9
    - xarray
    - matplotlib-base >=3.1
    - numpy >=1.17
    - pandas >=2.2.1
    - scipy
    - pytest
    - windrose
    - seaborn >=0.12.2
    - pyextremes
    - cartopy
    - python-docx
test:
  imports:
    - metocean_stats
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MET-OM/metocean-stats
  summary: 'Package for metocean statistics of hindcast/reanalysis data'
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://metocean-stats.readthedocs.io/
  dev_url: https://github.com/MET-OM/metocean-stats

extra:
  recipe-maintainers:
    - KonstantinChri
