{% set name = "metocean-stats" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 385493be3a06fb4b3efb76f7fb9e8ad077b680a1d365444539325cd1cf45a202

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.1
    - numpy >=1.17
    - pandas
    - scipy
    - pytest
    - windrose
    - seaborn >=0.12.2
    - metocean-api

test:
  imports:
    - metocean_stats
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MET-OM/metocean-stats
  summary: 'Package for metocean statistics of hindcast/reanalysis data'
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://metocean-stats.readthedocs.io/
  dev_url: https://github.com/MET-OM/metocean-stats

extra:
  recipe-maintainers:
    - KonstantinChri
