{% set name = "metocean-stats" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2a13a418c3592ca218f76fdeeb46c92132590838285e9105ec7ceb756f099efc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - xarray
    - matplotlib-base >=3.1
    - numpy >=1.17
    - pandas >=2.2.1
    - scipy
    - pytest
    - windrose
    - seaborn >=0.12.2
    - pyextremes
    - cartopy
    - python-docx
    - netcdf4
    - pydap
test:
  imports:
    - metocean_stats
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/MET-OM/metocean-stats
  summary: 'Package for metocean statistics of hindcast/reanalysis data'
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://metocean-stats.readthedocs.io/
  dev_url: https://github.com/MET-OM/metocean-stats

extra:
  recipe-maintainers:
    - KonstantinChri
