{% set name = "metocean-stats" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 101221e3df1a28144fce8a7b6503204ccbdb059c3cd2ccdecea8799af8b59efb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - xarray
    - matplotlib-base >=3.1
    - numpy >=1.17
    - pandas
    - scipy
    - pytest
    - windrose
    - seaborn >=0.12.2
    - metocean-api
    - pyextremes
    - virocon
    - scikit-learn
    - keras
    - tensorflow

test:
  imports:
    - metocean_stats
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MET-OM/metocean-stats
  summary: 'Package for metocean statistics of hindcast/reanalysis data'
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://metocean-stats.readthedocs.io/
  dev_url: https://github.com/MET-OM/metocean-stats

extra:
  recipe-maintainers:
    - KonstantinChri
